name: Convert Markdown to PDF

on:
  push:
    paths:
      - 'blogs/**/*.md'
  workflow_dispatch:
    

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Convert Markdown to PDF
        run: |
          cd blogs
          for file in *.md; do
            pandoc "$file" -o "${file%.md}.pdf"
          done

      - name: Create or Update Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'latest' # Use a consistent tag name to update the same release
          release_name: 'Latest PDFs'
          draft: false
          prerelease: false

      - name: Upload PDFs to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in blogs/*.pdf; do
            gh release upload latest "$file" --clobber
          done