name: superlinter- release the Possum!!

on:
  push:
    branches:
      - super-linter
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Super-Linter
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_MARKDOWN: true
          DEFAULT_BRANCH: main
          MARKDOWN_LINT_DISABLE_RULES: MD013 # Example to disable a specific rule
          MARKDOWN_LINT_FIX: true # Enable auto-fixing lint issues
          LINTER_RULES_PATH: .github/linters # Path to custom linter rules
          # Disable all other linters
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_ANSIBLE: false
          VALIDATE_ARM: false
          VALIDATE_BASH: false
          VALIDATE_CLOJURE: false
          VALIDATE_CMAKE: false
          VALIDATE_COFFEESCRIPT: false
          VALIDATE_CSHARP: false
          VALIDATE_CSS: false
          VALIDATE_DART: false
          VALIDATE_DOCKER: false
          VALIDATE_ENV: false
          VALIDATE_GO: false
          VALIDATE_GROOVY: false
          VALIDATE_HTML: false
          VALIDATE_JAVA: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSON: false
          VALIDATE_JSCPD: false
          VALIDATE_KOTLIN: false
          VALIDATE_LATEX: false
          VALIDATE_LUA: false
          VALIDATE_OPENAPI: false
          VALIDATE_PERL: false
          VALIDATE_PHP: false
          VALIDATE_POWERSHELL: false
          VALIDATE_PROTOBUF: false
          VALIDATE_PYTHON: false
          VALIDATE_R: false
          VALIDATE_RAKU: false
          VALIDATE_RUBY: false
          VALIDATE_RUST: false
          VALIDATE_SHELL_SHFMT: false
          VALIDATE_STATES: false
          VALIDATE_TERRAFORM: false
          VALIDATE_TSCPD: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_XML: false
          VALIDATE_YAML: false

 